package protocolgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

func generateGo(document openAPIDocument) ([]byte, error) {
	routes, err := document.routes()
	if err != nil {
		return nil, err
	}
	version, err := document.protocolVersion()
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by oc-control protocol generate; DO NOT EDIT.\n\n")
	output.WriteString("package protocol\n\n")
	output.WriteString("import \"time\"\n\n")
	fmt.Fprintf(&output, "const Version = %q\n\n", version)
	environment, err := document.environmentBindings()
	if err != nil {
		return nil, err
	}
	output.WriteString("const (\n")
	for _, binding := range environment {
		fmt.Fprintf(&output, "\tSidecarEnv%s = %q\n", goIdentifier(binding.Property), binding.Variable)
	}
	fmt.Fprintf(&output, "\tSidecarEnvironmentCount = %d\n", len(environment))
	output.WriteString(")\n\n")
	output.WriteString("const (\n")
	for _, candidate := range routes {
		name := goIdentifier(candidate.OperationID)
		fmt.Fprintf(&output, "\tRoute%s = %q\n", name, candidate.Path)
		fmt.Fprintf(&output, "\tMethod%s = %q\n", name, candidate.Method)
		fmt.Fprintf(&output, "\tPattern%s = %q\n", name, candidate.Method+" "+candidate.Path)
	}
	output.WriteString(")\n\n")

	events := document.eventValues()
	output.WriteString("type EventType string\n\nconst (\n")
	for _, event := range events {
		fmt.Fprintf(&output, "\tEvent%s EventType = %q\n", goIdentifier(event), event)
	}
	output.WriteString(")\n\n")

	for _, name := range document.schemaNames() {
		candidate := document.Components.Schemas[name]
		if candidate.Type != "string" || len(candidate.Enum) == 0 {
			continue
		}
		fmt.Fprintf(&output, "type %s string\n\nconst (\n", name)
		for _, value := range candidate.Enum {
			encoded, err := literal(value)
			if err != nil {
				return nil, err
			}
			text, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("%s contains a non-string enum", name)
			}
			fmt.Fprintf(&output, "\t%s%s %s = %s\n", name, goIdentifier(text), name, encoded)
		}
		output.WriteString(")\n\n")
	}

	for _, name := range document.schemaNames() {
		candidate := document.Components.Schemas[name]
		if candidate.Type == "string" && len(candidate.Enum) > 0 {
			continue
		}
		if len(candidate.AnyOf) > 0 || len(candidate.OneOf) > 0 {
			candidate, err = document.mergedUnion(candidate)
			if err != nil {
				return nil, fmt.Errorf("generate %s: %w", name, err)
			}
		}
		if candidate.Type != "object" {
			continue
		}
		fmt.Fprintf(&output, "type %s struct {\n", name)
		required := stringSet(candidate.Required)
		propertyNames := make([]string, 0, len(candidate.Properties))
		for propertyName := range candidate.Properties {
			propertyNames = append(propertyNames, propertyName)
		}
		sort.Strings(propertyNames)
		for _, propertyName := range propertyNames {
			property := candidate.Properties[propertyName]
			fieldType, err := goType(propertyName, property, !required[propertyName])
			if err != nil {
				return nil, fmt.Errorf("generate %s.%s: %w", name, propertyName, err)
			}
			tag := propertyName
			if !required[propertyName] {
				tag += ",omitempty"
			}
			fmt.Fprintf(&output, "\t%s %s `json:%q`\n", goIdentifier(propertyName), fieldType, tag)
		}
		output.WriteString("}\n\n")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go bindings: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func goType(propertyName string, candidate schema, optional bool) (string, error) {
	if candidate.Ref == "" && len(candidate.AllOf) == 1 {
		return goType(propertyName, candidate.AllOf[0], optional)
	}
	if propertyName == "type" && len(candidate.Enum) == 1 {
		return "EventType", nil
	}
	if candidate.Ref != "" {
		name := referenceName(candidate.Ref)
		if optional && strings.HasSuffix(name, "Status") {
			return "*" + name, nil
		}
		return name, nil
	}
	if candidate.Items != nil || candidate.Type == "array" {
		if candidate.Items == nil {
			return "", fmt.Errorf("array has no items")
		}
		itemType, err := goType("", *candidate.Items, false)
		if err != nil {
			return "", err
		}
		return "[]" + itemType, nil
	}
	switch candidate.Type {
	case "string":
		if candidate.Format == "date-time" {
			if optional {
				return "*time.Time", nil
			}
			return "time.Time", nil
		}
		return "string", nil
	case "integer":
		if candidate.Format == "int64" {
			return "int64", nil
		}
		if candidate.Minimum != nil && *candidate.Minimum >= 0 && candidate.Format == "double-int" {
			return "uint64", nil
		}
		return "int", nil
	case "number":
		if len(candidate.Enum) > 0 {
			return "int", nil
		}
		return "float64", nil
	case "boolean":
		if optional {
			return "*bool", nil
		}
		return "bool", nil
	case "object":
		return "map[string]any", nil
	default:
		return "", fmt.Errorf("unsupported schema type %q", candidate.Type)
	}
}

func generateTypeScript(document openAPIDocument) ([]byte, error) {
	routes, err := document.routes()
	if err != nil {
		return nil, err
	}
	version, err := document.protocolVersion()
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by oc-control protocol generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const protocolVersion = %q as const;\n\n", version)
	environment, err := document.environmentBindings()
	if err != nil {
		return nil, err
	}
	output.WriteString("export const sidecarEnvironment = {\n")
	for _, binding := range environment {
		fmt.Fprintf(&output, "  %s: %q,\n", binding.Property, binding.Variable)
	}
	output.WriteString("} as const;\n\n")
	output.WriteString("export const operations = {\n")
	for _, candidate := range routes {
		fmt.Fprintf(&output, "  %s: { method: %q, path: %q },\n", candidate.OperationID, candidate.Method, candidate.Path)
	}
	output.WriteString("} as const;\n\n")

	events := document.eventValues()
	output.WriteString("export const eventType = {\n")
	for _, event := range events {
		fmt.Fprintf(&output, "  %s: %q,\n", typescriptIdentifier(event), event)
	}
	output.WriteString("} as const;\n\n")
	output.WriteString("export type EventType = typeof eventType[keyof typeof eventType];\n\n")

	for _, name := range document.schemaNames() {
		candidate := document.Components.Schemas[name]
		if candidate.Type != "string" || len(candidate.Enum) == 0 {
			continue
		}
		values := make([]string, 0, len(candidate.Enum))
		for _, value := range candidate.Enum {
			encoded, err := literal(value)
			if err != nil {
				return nil, err
			}
			values = append(values, encoded)
		}
		fmt.Fprintf(&output, "export type %s = %s;\n\n", name, strings.Join(values, " | "))
		fmt.Fprintf(&output, "export const %s = {\n", typescriptIdentifier(name))
		for _, value := range candidate.Enum {
			text, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("%s contains a non-string enum", name)
			}
			encoded, _ := literal(value)
			fmt.Fprintf(&output, "  %s: %s,\n", typescriptIdentifier(text), encoded)
		}
		fmt.Fprintf(&output, "} as const satisfies Record<string, %s>;\n\n", name)
	}

	for _, name := range document.schemaNames() {
		candidate := document.Components.Schemas[name]
		if candidate.Type == "string" && len(candidate.Enum) > 0 {
			continue
		}
		variants := candidate.AnyOf
		if len(variants) == 0 {
			variants = candidate.OneOf
		}
		if len(variants) > 0 {
			members := make([]string, 0, len(variants))
			for _, variant := range variants {
				if variant.Ref == "" {
					return nil, fmt.Errorf("generate %s: inline union members are unsupported", name)
				}
				members = append(members, referenceName(variant.Ref))
			}
			fmt.Fprintf(&output, "export type %s = %s;\n\n", name, strings.Join(members, " | "))
			continue
		}
		if candidate.Type != "object" {
			continue
		}
		fmt.Fprintf(&output, "export type %s = {\n", name)
		required := stringSet(candidate.Required)
		propertyNames := make([]string, 0, len(candidate.Properties))
		for propertyName := range candidate.Properties {
			propertyNames = append(propertyNames, propertyName)
		}
		sort.Strings(propertyNames)
		for _, propertyName := range propertyNames {
			fieldType, err := typescriptType(propertyName, candidate.Properties[propertyName])
			if err != nil {
				return nil, fmt.Errorf("generate %s.%s: %w", name, propertyName, err)
			}
			optional := ""
			if !required[propertyName] {
				optional = "?"
			}
			fmt.Fprintf(&output, "  %s%s: %s;\n", propertyName, optional, fieldType)
		}
		output.WriteString("};\n\n")
	}
	return append(bytes.TrimRight(output.Bytes(), "\n"), '\n'), nil
}

func typescriptType(propertyName string, candidate schema) (string, error) {
	if candidate.Ref == "" && len(candidate.AllOf) == 1 {
		return typescriptType(propertyName, candidate.AllOf[0])
	}
	if candidate.Ref != "" {
		return referenceName(candidate.Ref), nil
	}
	if candidate.Items != nil || candidate.Type == "array" {
		if candidate.Items == nil {
			return "", fmt.Errorf("array has no items")
		}
		itemType, err := typescriptType("", *candidate.Items)
		if err != nil {
			return "", err
		}
		return "Array<" + itemType + ">", nil
	}
	if len(candidate.Enum) > 0 {
		values := make([]string, 0, len(candidate.Enum))
		for _, value := range candidate.Enum {
			encoded, err := literal(value)
			if err != nil {
				return "", err
			}
			values = append(values, encoded)
		}
		return strings.Join(values, " | "), nil
	}
	switch candidate.Type {
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "object":
		return "Record<string, unknown>", nil
	default:
		return "", fmt.Errorf("unsupported schema type %q", candidate.Type)
	}
}
