// Code generated by oc-control protocol generate; DO NOT EDIT.

export const protocolVersion = "sidecar.v1" as const;

export const sidecarEnvironment = {
  channel: "OC_SIDECAR_CHANNEL",
  control: "OC_SIDECAR_CONTROL",
  mode: "OC_SIDECAR_MODE",
  namespace: "OC_SIDECAR_NAMESPACE",
  source: "OC_SIDECAR_SOURCE",
  token: "OC_SIDECAR_TOKEN",
} as const;

export const operations = {
  broadcastControl: { method: "POST", path: "/v1/control" },
  delegateSidecarCapability: { method: "POST", path: "/v1/capabilities/sidecar" },
  health: { method: "GET", path: "/v1/health" },
  prepareLatestUpdate: { method: "POST", path: "/v1/update/transition" },
  registerSession: { method: "GET", path: "/v1/sessions/register" },
  renewCapability: { method: "POST", path: "/v1/capabilities/renew" },
  status: { method: "GET", path: "/v1/status" },
} as const;

export const eventType = {
  command: "command",
  endpoint: "endpoint",
  exiting: "exiting",
  heartbeat: "heartbeat",
  register: "register",
  registered: "registered",
  state: "state",
  status: "status",
} as const;

export type EventType = typeof eventType[keyof typeof eventType];

export type Capability = "observe" | "runtime-ready" | "lifecycle" | "update-transition" | "delegate-sidecar";

export const capability = {
  observe: "observe",
  runtimeReady: "runtime-ready",
  lifecycle: "lifecycle",
  updateTransition: "update-transition",
  delegateSidecar: "delegate-sidecar",
} as const satisfies Record<string, Capability>;

export type ControlCommand = "show" | "shutdown";

export const controlCommand = {
  show: "show",
  shutdown: "shutdown",
} as const satisfies Record<string, ControlCommand>;

export type Role = "owner" | "runtime" | "sidecar" | "observer";

export const role = {
  owner: "owner",
  runtime: "runtime",
  sidecar: "sidecar",
  observer: "observer",
} as const satisfies Record<string, Role>;

export type UpdateAction = "prepare-latest";

export const updateAction = {
  prepareLatest: "prepare-latest",
} as const satisfies Record<string, UpdateAction>;

export type UpdateStatus = "current" | "prepared";

export const updateStatus = {
  current: "current",
  prepared: "prepared",
} as const satisfies Record<string, UpdateStatus>;

export type ClientEvent = RegisterEvent | HeartbeatEvent | EndpointEvent | StateEvent | ExitingEvent;

export type CommandEvent = {
  command: ControlCommand;
  type: "command";
};

export type ControlDescriptor = {
  address: string;
  generation: number;
  pid: number;
  protocol: "sidecar.v1";
  schema: 1;
  sessionId: string;
  startedAt: string;
};

export type ControlRequest = {
  command: ControlCommand;
};

export type ControlResponse = {
  accepted: number;
};

export type DelegateRequest = {
  capabilities?: Array<Capability>;
  subject: string;
  ttlSeconds?: number;
};

export type DelegateResponse = {
  expiresAt: string;
  subject: string;
  token: string;
};

export type Endpoint = {
  name: string;
  url: string;
};

export type EndpointEvent = {
  name: string;
  type: "endpoint";
  url: string;
};

export type ErrorResponse = {
  error: string;
};

export type ExitingEvent = {
  code: number;
  type: "exiting";
};

export type Health = {
  generation: number;
  protocol: "sidecar.v1";
  schema: 1;
  sessionId: string;
};

export type HeartbeatEvent = {
  type: "heartbeat";
};

export type RegisterEvent = {
  app: string;
  channel: string;
  generation: number;
  instanceId: string;
  mode: string;
  namespace: string;
  sessionId: string;
  source: string;
  type: "register";
};

export type RegisteredEvent = {
  type: "registered";
};

export type RenewRequest = {
  ttlSeconds?: number;
};

export type RenewResponse = {
  expiresAt: string;
  subject: string;
  token: string;
};

export type ServerEvent = RegisteredEvent | CommandEvent | StatusEvent;

export type SessionStatus = {
  app: string;
  connectedAt: string;
  endpoints?: Array<Endpoint>;
  instanceId: string;
  lastHeartbeat: string;
  mode: string;
  ready: boolean;
  source: string;
  subject: string;
};

export type SidecarEvent = ClientEvent | ServerEvent;

export type SidecarLaunch = {
  channel: string;
  control: ControlDescriptor;
  mode: string;
  namespace: string;
  source: string;
  token: string;
};

export type StateEvent = {
  ready: boolean;
  type: "state";
};

export type Status = {
  channel: string;
  generation: number;
  namespace: string;
  revision: number;
  schema: 1;
  sessionId: string;
  sessions: Array<SessionStatus>;
};

export type StatusEvent = {
  status: Status;
  type: "status";
};

export type UpdateTransitionRequest = {
  action: UpdateAction;
};

export type UpdateTransitionResponse = {
  restartRequired: boolean;
  status: UpdateStatus;
  version: string;
};
