// Code generated by oc-control protocol generate; DO NOT EDIT.

import { decodeProtocolValue, readProtocolEnvironment } from "./runtime.js";
import type { ProtocolSchemas } from "./runtime.js";

export const protocolVersion = "sidecar.v1" as const;

export const sidecarEnvironment = {
  app: "OC_SIDECAR_APP",
  channel: "OC_SIDECAR_CHANNEL",
  control: "OC_SIDECAR_CONTROL",
  mode: "OC_SIDECAR_MODE",
  namespace: "OC_SIDECAR_NAMESPACE",
  presentation: "OC_SIDECAR_PRESENTATION",
  source: "OC_SIDECAR_SOURCE",
  token: "OC_SIDECAR_TOKEN",
} as const;

export const operations = {
  broadcastControl: { method: "POST", path: "/v1/control", scheme: "http" },
  delegateSidecarCapability: { method: "POST", path: "/v1/capabilities/sidecar", scheme: "http" },
  health: { method: "GET", path: "/v1/health", scheme: "http" },
  prepareLatestUpdate: { method: "POST", path: "/v1/update/transition", scheme: "http" },
  registerSession: { method: "GET", path: "/v1/sessions/register", scheme: "ws" },
  renewCapability: { method: "POST", path: "/v1/capabilities/renew", scheme: "http" },
  status: { method: "GET", path: "/v1/status", scheme: "http" },
} as const;

export const eventType = {
  command: "command",
  endpoint: "endpoint",
  exiting: "exiting",
  heartbeat: "heartbeat",
  register: "register",
  registered: "registered",
  state: "state",
  status: "status",
} as const;

export type EventType = typeof eventType[keyof typeof eventType];

export type Capability = "observe" | "runtime-ready" | "lifecycle" | "update-transition" | "delegate-sidecar";

export const capability = {
  observe: "observe",
  runtimeReady: "runtime-ready",
  lifecycle: "lifecycle",
  updateTransition: "update-transition",
  delegateSidecar: "delegate-sidecar",
} as const satisfies Record<string, Capability>;

export type ControlCommand = "show" | "shutdown";

export const controlCommand = {
  show: "show",
  shutdown: "shutdown",
} as const satisfies Record<string, ControlCommand>;

export type LifecycleMode = "production" | "packaged" | "dev" | "harness";

export const lifecycleMode = {
  production: "production",
  packaged: "packaged",
  dev: "dev",
  harness: "harness",
} as const satisfies Record<string, LifecycleMode>;

export type Presentation = "interactive" | "headless";

export const presentation = {
  interactive: "interactive",
  headless: "headless",
} as const satisfies Record<string, Presentation>;

export type Role = "owner" | "runtime" | "sidecar" | "observer";

export const role = {
  owner: "owner",
  runtime: "runtime",
  sidecar: "sidecar",
  observer: "observer",
} as const satisfies Record<string, Role>;

export type UpdateAction = "prepare-latest";

export const updateAction = {
  prepareLatest: "prepare-latest",
} as const satisfies Record<string, UpdateAction>;

export type UpdateStatus = "current" | "prepared";

export const updateStatus = {
  current: "current",
  prepared: "prepared",
} as const satisfies Record<string, UpdateStatus>;

export type ClientEvent = RegisterEvent | HeartbeatEvent | EndpointEvent | StateEvent | ExitingEvent;

export type CommandEvent = {
  command: ControlCommand;
  type: "command";
};

export type ControlDescriptor = {
  address: string;
  generation: number;
  pid: number;
  protocol: "sidecar.v1";
  schema: 1;
  sessionId: string;
  startedAt: string;
};

export type ControlRequest = {
  command: ControlCommand;
};

export type ControlResponse = {
  accepted: number;
};

export type DelegateRequest = {
  capabilities?: Array<Capability>;
  subject: string;
  ttlSeconds?: number;
};

export type DelegateResponse = {
  expiresAt: string;
  subject: string;
  token: string;
};

export type Endpoint = {
  name: string;
  url: string;
};

export type EndpointEvent = {
  name: string;
  type: "endpoint";
  url: string;
};

export type ErrorResponse = {
  error: string;
};

export type ExitingEvent = {
  code: number;
  type: "exiting";
};

export type Health = {
  generation: number;
  protocol: "sidecar.v1";
  schema: 1;
  sessionId: string;
};

export type HeartbeatEvent = {
  type: "heartbeat";
};

export type RegisterEvent = {
  app: string;
  channel: string;
  generation: number;
  instanceId: string;
  mode: LifecycleMode;
  namespace: string;
  sessionId: string;
  source: string;
  type: "register";
};

export type RegisteredEvent = {
  type: "registered";
};

export type RenewRequest = {
  ttlSeconds?: number;
};

export type RenewResponse = {
  expiresAt: string;
  subject: string;
  token: string;
};

export type ServerEvent = RegisteredEvent | CommandEvent | StatusEvent;

export type SessionStatus = {
  app: string;
  connectedAt: string;
  endpoints?: Array<Endpoint>;
  instanceId: string;
  lastHeartbeat: string;
  mode: LifecycleMode;
  ready: boolean;
  source: string;
  subject: string;
};

export type SidecarEvent = ClientEvent | ServerEvent;

export type SidecarLaunch = {
  app: string;
  channel: string;
  control: ControlDescriptor;
  mode: LifecycleMode;
  namespace: string;
  presentation: Presentation;
  source: string;
  token: string;
};

export type StateEvent = {
  ready: boolean;
  type: "state";
};

export type Status = {
  channel: string;
  generation: number;
  namespace: string;
  revision: number;
  schema: 1;
  sessionId: string;
  sessions: Array<SessionStatus>;
};

export type StatusEvent = {
  status: Status;
  type: "status";
};

export type UpdateTransitionRequest = {
  action: UpdateAction;
};

export type UpdateTransitionResponse = {
  restartRequired: boolean;
  status: UpdateStatus;
  version: string;
};

export const protocolSchemas = {
  "Capability": {
    "type": "string",
    "enum": [
      "observe",
      "runtime-ready",
      "lifecycle",
      "update-transition",
      "delegate-sidecar"
    ]
  },
  "ClientEvent": {
    "anyOf": [
      {
        "$ref": "#/components/schemas/RegisterEvent"
      },
      {
        "$ref": "#/components/schemas/HeartbeatEvent"
      },
      {
        "$ref": "#/components/schemas/EndpointEvent"
      },
      {
        "$ref": "#/components/schemas/StateEvent"
      },
      {
        "$ref": "#/components/schemas/ExitingEvent"
      }
    ]
  },
  "CommandEvent": {
    "type": "object",
    "properties": {
      "command": {
        "$ref": "#/components/schemas/ControlCommand"
      },
      "type": {
        "type": "string",
        "enum": [
          "command"
        ]
      }
    },
    "required": [
      "type",
      "command"
    ]
  },
  "ControlCommand": {
    "type": "string",
    "enum": [
      "show",
      "shutdown"
    ]
  },
  "ControlDescriptor": {
    "type": "object",
    "properties": {
      "address": {
        "type": "string",
        "minLength": 1
      },
      "generation": {
        "type": "integer",
        "format": "double-int",
        "minimum": 0
      },
      "pid": {
        "type": "integer",
        "format": "int32"
      },
      "protocol": {
        "type": "string",
        "enum": [
          "sidecar.v1"
        ]
      },
      "schema": {
        "type": "number",
        "enum": [
          1
        ]
      },
      "sessionId": {
        "type": "string",
        "minLength": 1
      },
      "startedAt": {
        "type": "string",
        "format": "date-time"
      }
    },
    "required": [
      "schema",
      "protocol",
      "address",
      "pid",
      "sessionId",
      "generation",
      "startedAt"
    ]
  },
  "ControlRequest": {
    "type": "object",
    "properties": {
      "command": {
        "$ref": "#/components/schemas/ControlCommand"
      }
    },
    "required": [
      "command"
    ]
  },
  "ControlResponse": {
    "type": "object",
    "properties": {
      "accepted": {
        "type": "integer",
        "format": "int32",
        "minimum": 0
      }
    },
    "required": [
      "accepted"
    ]
  },
  "DelegateRequest": {
    "type": "object",
    "properties": {
      "capabilities": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Capability"
        },
        "uniqueItems": true
      },
      "subject": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "ttlSeconds": {
        "type": "integer",
        "format": "int64",
        "minimum": 1,
        "maximum": 3600
      }
    },
    "required": [
      "subject"
    ]
  },
  "DelegateResponse": {
    "type": "object",
    "properties": {
      "expiresAt": {
        "type": "string",
        "format": "date-time"
      },
      "subject": {
        "type": "string"
      },
      "token": {
        "type": "string"
      }
    },
    "required": [
      "subject",
      "token",
      "expiresAt"
    ]
  },
  "Endpoint": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "name",
      "url"
    ]
  },
  "EndpointEvent": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "type": {
        "type": "string",
        "enum": [
          "endpoint"
        ]
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "type",
      "name",
      "url"
    ]
  },
  "ErrorResponse": {
    "type": "object",
    "properties": {
      "error": {
        "type": "string"
      }
    },
    "required": [
      "error"
    ]
  },
  "ExitingEvent": {
    "type": "object",
    "properties": {
      "code": {
        "type": "integer",
        "format": "int32"
      },
      "type": {
        "type": "string",
        "enum": [
          "exiting"
        ]
      }
    },
    "required": [
      "type",
      "code"
    ]
  },
  "Health": {
    "type": "object",
    "properties": {
      "generation": {
        "type": "integer",
        "format": "double-int",
        "minimum": 0
      },
      "protocol": {
        "type": "string",
        "enum": [
          "sidecar.v1"
        ]
      },
      "schema": {
        "type": "number",
        "enum": [
          1
        ]
      },
      "sessionId": {
        "type": "string",
        "minLength": 1
      }
    },
    "required": [
      "schema",
      "protocol",
      "sessionId",
      "generation"
    ]
  },
  "HeartbeatEvent": {
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "enum": [
          "heartbeat"
        ]
      }
    },
    "required": [
      "type"
    ]
  },
  "LifecycleMode": {
    "type": "string",
    "enum": [
      "production",
      "packaged",
      "dev",
      "harness"
    ]
  },
  "Presentation": {
    "type": "string",
    "enum": [
      "interactive",
      "headless"
    ]
  },
  "RegisterEvent": {
    "type": "object",
    "properties": {
      "app": {
        "type": "string",
        "minLength": 1
      },
      "channel": {
        "type": "string",
        "minLength": 1
      },
      "generation": {
        "type": "integer",
        "format": "double-int",
        "minimum": 0
      },
      "instanceId": {
        "type": "string",
        "minLength": 1
      },
      "mode": {
        "$ref": "#/components/schemas/LifecycleMode"
      },
      "namespace": {
        "type": "string",
        "minLength": 1
      },
      "sessionId": {
        "type": "string",
        "minLength": 1
      },
      "source": {
        "type": "string",
        "minLength": 1
      },
      "type": {
        "type": "string",
        "enum": [
          "register"
        ]
      }
    },
    "required": [
      "type",
      "channel",
      "namespace",
      "sessionId",
      "generation",
      "app",
      "instanceId",
      "mode",
      "source"
    ]
  },
  "RegisteredEvent": {
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "enum": [
          "registered"
        ]
      }
    },
    "required": [
      "type"
    ]
  },
  "RenewRequest": {
    "type": "object",
    "properties": {
      "ttlSeconds": {
        "type": "integer",
        "format": "int64",
        "minimum": 1,
        "maximum": 604800
      }
    }
  },
  "RenewResponse": {
    "type": "object",
    "properties": {
      "expiresAt": {
        "type": "string",
        "format": "date-time"
      },
      "subject": {
        "type": "string"
      },
      "token": {
        "type": "string"
      }
    },
    "required": [
      "subject",
      "token",
      "expiresAt"
    ]
  },
  "Role": {
    "type": "string",
    "enum": [
      "owner",
      "runtime",
      "sidecar",
      "observer"
    ]
  },
  "ServerEvent": {
    "anyOf": [
      {
        "$ref": "#/components/schemas/RegisteredEvent"
      },
      {
        "$ref": "#/components/schemas/CommandEvent"
      },
      {
        "$ref": "#/components/schemas/StatusEvent"
      }
    ]
  },
  "SessionStatus": {
    "type": "object",
    "properties": {
      "app": {
        "type": "string",
        "minLength": 1
      },
      "connectedAt": {
        "type": "string",
        "format": "date-time"
      },
      "endpoints": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Endpoint"
        }
      },
      "instanceId": {
        "type": "string",
        "minLength": 1
      },
      "lastHeartbeat": {
        "type": "string",
        "format": "date-time"
      },
      "mode": {
        "$ref": "#/components/schemas/LifecycleMode"
      },
      "ready": {
        "type": "boolean"
      },
      "source": {
        "type": "string",
        "minLength": 1
      },
      "subject": {
        "type": "string",
        "minLength": 1
      }
    },
    "required": [
      "subject",
      "app",
      "instanceId",
      "mode",
      "source",
      "ready",
      "connectedAt",
      "lastHeartbeat"
    ]
  },
  "SidecarEvent": {
    "anyOf": [
      {
        "$ref": "#/components/schemas/ClientEvent"
      },
      {
        "$ref": "#/components/schemas/ServerEvent"
      }
    ]
  },
  "SidecarLaunch": {
    "type": "object",
    "properties": {
      "app": {
        "type": "string",
        "minLength": 1,
        "x-environment": "OC_SIDECAR_APP"
      },
      "channel": {
        "type": "string",
        "minLength": 1,
        "x-environment": "OC_SIDECAR_CHANNEL"
      },
      "control": {
        "allOf": [
          {
            "$ref": "#/components/schemas/ControlDescriptor"
          }
        ],
        "x-environment": "OC_SIDECAR_CONTROL"
      },
      "mode": {
        "allOf": [
          {
            "$ref": "#/components/schemas/LifecycleMode"
          }
        ],
        "x-environment": "OC_SIDECAR_MODE"
      },
      "namespace": {
        "type": "string",
        "minLength": 1,
        "x-environment": "OC_SIDECAR_NAMESPACE"
      },
      "presentation": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Presentation"
          }
        ],
        "x-environment": "OC_SIDECAR_PRESENTATION"
      },
      "source": {
        "type": "string",
        "minLength": 1,
        "x-environment": "OC_SIDECAR_SOURCE"
      },
      "token": {
        "type": "string",
        "minLength": 1,
        "x-environment": "OC_SIDECAR_TOKEN"
      }
    },
    "required": [
      "app",
      "control",
      "token",
      "channel",
      "namespace",
      "mode",
      "presentation",
      "source"
    ]
  },
  "StateEvent": {
    "type": "object",
    "properties": {
      "ready": {
        "type": "boolean"
      },
      "type": {
        "type": "string",
        "enum": [
          "state"
        ]
      }
    },
    "required": [
      "type",
      "ready"
    ]
  },
  "Status": {
    "type": "object",
    "properties": {
      "channel": {
        "type": "string",
        "minLength": 1
      },
      "generation": {
        "type": "integer",
        "format": "double-int",
        "minimum": 0
      },
      "namespace": {
        "type": "string",
        "minLength": 1
      },
      "revision": {
        "type": "integer",
        "format": "double-int",
        "minimum": 0
      },
      "schema": {
        "type": "number",
        "enum": [
          1
        ]
      },
      "sessionId": {
        "type": "string",
        "minLength": 1
      },
      "sessions": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/SessionStatus"
        }
      }
    },
    "required": [
      "schema",
      "revision",
      "channel",
      "namespace",
      "sessionId",
      "generation",
      "sessions"
    ]
  },
  "StatusEvent": {
    "type": "object",
    "properties": {
      "status": {
        "$ref": "#/components/schemas/Status"
      },
      "type": {
        "type": "string",
        "enum": [
          "status"
        ]
      }
    },
    "required": [
      "type",
      "status"
    ]
  },
  "UpdateAction": {
    "type": "string",
    "enum": [
      "prepare-latest"
    ]
  },
  "UpdateStatus": {
    "type": "string",
    "enum": [
      "current",
      "prepared"
    ]
  },
  "UpdateTransitionRequest": {
    "type": "object",
    "properties": {
      "action": {
        "$ref": "#/components/schemas/UpdateAction"
      }
    },
    "required": [
      "action"
    ]
  },
  "UpdateTransitionResponse": {
    "type": "object",
    "properties": {
      "restartRequired": {
        "type": "boolean"
      },
      "status": {
        "$ref": "#/components/schemas/UpdateStatus"
      },
      "version": {
        "type": "string"
      }
    },
    "required": [
      "status",
      "version",
      "restartRequired"
    ]
  }
} as const satisfies ProtocolSchemas;

export function decodeCapability(value: unknown): Capability {
  return decodeProtocolValue<Capability>("Capability", protocolSchemas, value);
}

export function decodeClientEvent(value: unknown): ClientEvent {
  return decodeProtocolValue<ClientEvent>("ClientEvent", protocolSchemas, value);
}

export function decodeCommandEvent(value: unknown): CommandEvent {
  return decodeProtocolValue<CommandEvent>("CommandEvent", protocolSchemas, value);
}

export function decodeControlCommand(value: unknown): ControlCommand {
  return decodeProtocolValue<ControlCommand>("ControlCommand", protocolSchemas, value);
}

export function decodeControlDescriptor(value: unknown): ControlDescriptor {
  return decodeProtocolValue<ControlDescriptor>("ControlDescriptor", protocolSchemas, value);
}

export function decodeControlRequest(value: unknown): ControlRequest {
  return decodeProtocolValue<ControlRequest>("ControlRequest", protocolSchemas, value);
}

export function decodeControlResponse(value: unknown): ControlResponse {
  return decodeProtocolValue<ControlResponse>("ControlResponse", protocolSchemas, value);
}

export function decodeDelegateRequest(value: unknown): DelegateRequest {
  return decodeProtocolValue<DelegateRequest>("DelegateRequest", protocolSchemas, value);
}

export function decodeDelegateResponse(value: unknown): DelegateResponse {
  return decodeProtocolValue<DelegateResponse>("DelegateResponse", protocolSchemas, value);
}

export function decodeEndpoint(value: unknown): Endpoint {
  return decodeProtocolValue<Endpoint>("Endpoint", protocolSchemas, value);
}

export function decodeEndpointEvent(value: unknown): EndpointEvent {
  return decodeProtocolValue<EndpointEvent>("EndpointEvent", protocolSchemas, value);
}

export function decodeErrorResponse(value: unknown): ErrorResponse {
  return decodeProtocolValue<ErrorResponse>("ErrorResponse", protocolSchemas, value);
}

export function decodeExitingEvent(value: unknown): ExitingEvent {
  return decodeProtocolValue<ExitingEvent>("ExitingEvent", protocolSchemas, value);
}

export function decodeHealth(value: unknown): Health {
  return decodeProtocolValue<Health>("Health", protocolSchemas, value);
}

export function decodeHeartbeatEvent(value: unknown): HeartbeatEvent {
  return decodeProtocolValue<HeartbeatEvent>("HeartbeatEvent", protocolSchemas, value);
}

export function decodeLifecycleMode(value: unknown): LifecycleMode {
  return decodeProtocolValue<LifecycleMode>("LifecycleMode", protocolSchemas, value);
}

export function decodePresentation(value: unknown): Presentation {
  return decodeProtocolValue<Presentation>("Presentation", protocolSchemas, value);
}

export function decodeRegisterEvent(value: unknown): RegisterEvent {
  return decodeProtocolValue<RegisterEvent>("RegisterEvent", protocolSchemas, value);
}

export function decodeRegisteredEvent(value: unknown): RegisteredEvent {
  return decodeProtocolValue<RegisteredEvent>("RegisteredEvent", protocolSchemas, value);
}

export function decodeRenewRequest(value: unknown): RenewRequest {
  return decodeProtocolValue<RenewRequest>("RenewRequest", protocolSchemas, value);
}

export function decodeRenewResponse(value: unknown): RenewResponse {
  return decodeProtocolValue<RenewResponse>("RenewResponse", protocolSchemas, value);
}

export function decodeRole(value: unknown): Role {
  return decodeProtocolValue<Role>("Role", protocolSchemas, value);
}

export function decodeServerEvent(value: unknown): ServerEvent {
  return decodeProtocolValue<ServerEvent>("ServerEvent", protocolSchemas, value);
}

export function decodeSessionStatus(value: unknown): SessionStatus {
  return decodeProtocolValue<SessionStatus>("SessionStatus", protocolSchemas, value);
}

export function decodeSidecarEvent(value: unknown): SidecarEvent {
  return decodeProtocolValue<SidecarEvent>("SidecarEvent", protocolSchemas, value);
}

export function decodeSidecarLaunch(value: unknown): SidecarLaunch {
  return decodeProtocolValue<SidecarLaunch>("SidecarLaunch", protocolSchemas, value);
}

export function decodeStateEvent(value: unknown): StateEvent {
  return decodeProtocolValue<StateEvent>("StateEvent", protocolSchemas, value);
}

export function decodeStatus(value: unknown): Status {
  return decodeProtocolValue<Status>("Status", protocolSchemas, value);
}

export function decodeStatusEvent(value: unknown): StatusEvent {
  return decodeProtocolValue<StatusEvent>("StatusEvent", protocolSchemas, value);
}

export function decodeUpdateAction(value: unknown): UpdateAction {
  return decodeProtocolValue<UpdateAction>("UpdateAction", protocolSchemas, value);
}

export function decodeUpdateStatus(value: unknown): UpdateStatus {
  return decodeProtocolValue<UpdateStatus>("UpdateStatus", protocolSchemas, value);
}

export function decodeUpdateTransitionRequest(value: unknown): UpdateTransitionRequest {
  return decodeProtocolValue<UpdateTransitionRequest>("UpdateTransitionRequest", protocolSchemas, value);
}

export function decodeUpdateTransitionResponse(value: unknown): UpdateTransitionResponse {
  return decodeProtocolValue<UpdateTransitionResponse>("UpdateTransitionResponse", protocolSchemas, value);
}

export type ProtocolEnvironment = Readonly<Record<string, string | undefined>>;

export function decodeSidecarLaunchEnvironment(environment: ProtocolEnvironment): SidecarLaunch {
  const value: Record<string, unknown> = {};
  value.app = readProtocolEnvironment(environment, sidecarEnvironment.app, "text");
  value.channel = readProtocolEnvironment(environment, sidecarEnvironment.channel, "text");
  value.control = readProtocolEnvironment(environment, sidecarEnvironment.control, "json");
  value.mode = readProtocolEnvironment(environment, sidecarEnvironment.mode, "text");
  value.namespace = readProtocolEnvironment(environment, sidecarEnvironment.namespace, "text");
  value.presentation = readProtocolEnvironment(environment, sidecarEnvironment.presentation, "text");
  value.source = readProtocolEnvironment(environment, sidecarEnvironment.source, "text");
  value.token = readProtocolEnvironment(environment, sidecarEnvironment.token, "text");
  return decodeSidecarLaunch(value);
}
