// Code generated by oc-control protocol generate; DO NOT EDIT.

package protocol

import "time"

const Version = "sidecar.v1"

const (
	SidecarEnvApp           = "OC_SIDECAR_APP"
	SidecarEnvChannel       = "OC_SIDECAR_CHANNEL"
	SidecarEnvControl       = "OC_SIDECAR_CONTROL"
	SidecarEnvDataDir       = "OC_SIDECAR_DATA_DIR"
	SidecarEnvMode          = "OC_SIDECAR_MODE"
	SidecarEnvNamespace     = "OC_SIDECAR_NAMESPACE"
	SidecarEnvPresentation  = "OC_SIDECAR_PRESENTATION"
	SidecarEnvSource        = "OC_SIDECAR_SOURCE"
	SidecarEnvToken         = "OC_SIDECAR_TOKEN"
	SidecarEnvironmentCount = 9
)

const (
	RouteBroadcastControl            = "/v1/control"
	MethodBroadcastControl           = "POST"
	SchemeBroadcastControl           = "http"
	PatternBroadcastControl          = "POST /v1/control"
	RouteDelegateSidecarCapability   = "/v1/capabilities/sidecar"
	MethodDelegateSidecarCapability  = "POST"
	SchemeDelegateSidecarCapability  = "http"
	PatternDelegateSidecarCapability = "POST /v1/capabilities/sidecar"
	RouteHealth                      = "/v1/health"
	MethodHealth                     = "GET"
	SchemeHealth                     = "http"
	PatternHealth                    = "GET /v1/health"
	RoutePrepareLatestUpdate         = "/v1/update/transition"
	MethodPrepareLatestUpdate        = "POST"
	SchemePrepareLatestUpdate        = "http"
	PatternPrepareLatestUpdate       = "POST /v1/update/transition"
	RouteRegisterSession             = "/v1/sessions/register"
	MethodRegisterSession            = "GET"
	SchemeRegisterSession            = "ws"
	PatternRegisterSession           = "GET /v1/sessions/register"
	RouteRenewCapability             = "/v1/capabilities/renew"
	MethodRenewCapability            = "POST"
	SchemeRenewCapability            = "http"
	PatternRenewCapability           = "POST /v1/capabilities/renew"
	RouteStatus                      = "/v1/status"
	MethodStatus                     = "GET"
	SchemeStatus                     = "http"
	PatternStatus                    = "GET /v1/status"
)

type EventType string

const (
	EventCommand    EventType = "command"
	EventEndpoint   EventType = "endpoint"
	EventExiting    EventType = "exiting"
	EventHeartbeat  EventType = "heartbeat"
	EventRegister   EventType = "register"
	EventRegistered EventType = "registered"
	EventState      EventType = "state"
	EventStatus     EventType = "status"
)

type Capability string

const (
	CapabilityObserve          Capability = "observe"
	CapabilityRuntimeReady     Capability = "runtime-ready"
	CapabilityLifecycle        Capability = "lifecycle"
	CapabilityUpdateTransition Capability = "update-transition"
	CapabilityDelegateSidecar  Capability = "delegate-sidecar"
)

type ControlCommand string

const (
	ControlCommandShow     ControlCommand = "show"
	ControlCommandShutdown ControlCommand = "shutdown"
)

type LifecycleMode string

const (
	LifecycleModeProduction LifecycleMode = "production"
	LifecycleModePackaged   LifecycleMode = "packaged"
	LifecycleModeDev        LifecycleMode = "dev"
	LifecycleModeHarness    LifecycleMode = "harness"
)

type Presentation string

const (
	PresentationInteractive Presentation = "interactive"
	PresentationHeadless    Presentation = "headless"
)

type Role string

const (
	RoleOwner    Role = "owner"
	RoleRuntime  Role = "runtime"
	RoleSidecar  Role = "sidecar"
	RoleObserver Role = "observer"
)

type UpdateAction string

const (
	UpdateActionPrepareLatest UpdateAction = "prepare-latest"
)

type UpdateStatus string

const (
	UpdateStatusCurrent  UpdateStatus = "current"
	UpdateStatusPrepared UpdateStatus = "prepared"
)

type ClientEvent struct {
	App        string        `json:"app,omitempty"`
	Channel    string        `json:"channel,omitempty"`
	Code       int           `json:"code,omitempty"`
	Generation uint64        `json:"generation,omitempty"`
	InstanceID string        `json:"instanceId,omitempty"`
	Mode       LifecycleMode `json:"mode,omitempty"`
	Name       string        `json:"name,omitempty"`
	Namespace  string        `json:"namespace,omitempty"`
	Ready      *bool         `json:"ready,omitempty"`
	SessionID  string        `json:"sessionId,omitempty"`
	Source     string        `json:"source,omitempty"`
	Type       EventType     `json:"type"`
	URL        string        `json:"url,omitempty"`
}

type CommandEvent struct {
	Command ControlCommand `json:"command"`
	Type    EventType      `json:"type"`
}

type ControlDescriptor struct {
	Address    string    `json:"address"`
	Generation uint64    `json:"generation"`
	PID        int       `json:"pid"`
	Protocol   string    `json:"protocol"`
	Schema     int       `json:"schema"`
	SessionID  string    `json:"sessionId"`
	StartedAt  time.Time `json:"startedAt"`
}

type ControlRequest struct {
	Command ControlCommand `json:"command"`
}

type ControlResponse struct {
	Accepted int `json:"accepted"`
}

type DelegateRequest struct {
	Capabilities []Capability `json:"capabilities,omitempty"`
	Subject      string       `json:"subject"`
	TTLSeconds   int64        `json:"ttlSeconds,omitempty"`
}

type DelegateResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Subject   string    `json:"subject"`
	Token     string    `json:"token"`
}

type Endpoint struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type EndpointEvent struct {
	Name string    `json:"name"`
	Type EventType `json:"type"`
	URL  string    `json:"url"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

type ExitingEvent struct {
	Code int       `json:"code"`
	Type EventType `json:"type"`
}

type Health struct {
	Generation uint64 `json:"generation"`
	Protocol   string `json:"protocol"`
	Schema     int    `json:"schema"`
	SessionID  string `json:"sessionId"`
}

type HeartbeatEvent struct {
	Type EventType `json:"type"`
}

type RegisterEvent struct {
	App        string        `json:"app"`
	Channel    string        `json:"channel"`
	Generation uint64        `json:"generation"`
	InstanceID string        `json:"instanceId"`
	Mode       LifecycleMode `json:"mode"`
	Namespace  string        `json:"namespace"`
	SessionID  string        `json:"sessionId"`
	Source     string        `json:"source"`
	Type       EventType     `json:"type"`
}

type RegisteredEvent struct {
	Type EventType `json:"type"`
}

type RenewRequest struct {
	TTLSeconds int64 `json:"ttlSeconds,omitempty"`
}

type RenewResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Subject   string    `json:"subject"`
	Token     string    `json:"token"`
}

type ServerEvent struct {
	Command ControlCommand `json:"command,omitempty"`
	Status  *Status        `json:"status,omitempty"`
	Type    EventType      `json:"type"`
}

type SessionStatus struct {
	App           string        `json:"app"`
	ConnectedAt   time.Time     `json:"connectedAt"`
	Endpoints     []Endpoint    `json:"endpoints,omitempty"`
	InstanceID    string        `json:"instanceId"`
	LastHeartbeat time.Time     `json:"lastHeartbeat"`
	Mode          LifecycleMode `json:"mode"`
	Ready         bool          `json:"ready"`
	Source        string        `json:"source"`
	Subject       string        `json:"subject"`
}

type SidecarEvent struct {
	App        string         `json:"app,omitempty"`
	Channel    string         `json:"channel,omitempty"`
	Code       int            `json:"code,omitempty"`
	Command    ControlCommand `json:"command,omitempty"`
	Generation uint64         `json:"generation,omitempty"`
	InstanceID string         `json:"instanceId,omitempty"`
	Mode       LifecycleMode  `json:"mode,omitempty"`
	Name       string         `json:"name,omitempty"`
	Namespace  string         `json:"namespace,omitempty"`
	Ready      *bool          `json:"ready,omitempty"`
	SessionID  string         `json:"sessionId,omitempty"`
	Source     string         `json:"source,omitempty"`
	Status     *Status        `json:"status,omitempty"`
	Type       EventType      `json:"type"`
	URL        string         `json:"url,omitempty"`
}

type SidecarLaunch struct {
	App          string            `json:"app"`
	Channel      string            `json:"channel"`
	Control      ControlDescriptor `json:"control"`
	DataDir      string            `json:"dataDir"`
	Mode         LifecycleMode     `json:"mode"`
	Namespace    string            `json:"namespace"`
	Presentation Presentation      `json:"presentation"`
	Source       string            `json:"source"`
	Token        string            `json:"token"`
}

type StateEvent struct {
	Ready bool      `json:"ready"`
	Type  EventType `json:"type"`
}

type Status struct {
	Channel    string          `json:"channel"`
	Generation uint64          `json:"generation"`
	Namespace  string          `json:"namespace"`
	Revision   uint64          `json:"revision"`
	Schema     int             `json:"schema"`
	SessionID  string          `json:"sessionId"`
	Sessions   []SessionStatus `json:"sessions"`
}

type StatusEvent struct {
	Status Status    `json:"status"`
	Type   EventType `json:"type"`
}

type UpdateTransitionRequest struct {
	Action UpdateAction `json:"action"`
}

type UpdateTransitionResponse struct {
	RestartRequired bool         `json:"restartRequired"`
	Status          UpdateStatus `json:"status"`
	Version         string       `json:"version"`
}
